# application configuration
#
application:
  version: 0.5.3

# general spring boot and server configuration
#
server:
  port: 8090

  ssl:
    enabled: false

spring:
  task:
    execution:
      pool:
        queue-capacity: 128
        max-size: 128
    scheduling:
      thread-name-prefix: "tika~"
      pool:
        size: 16

  servlet:
    multipart:
      max-file-size: 32768MB
      max-request-size: 32768MB
      file-size-threshold: 16384MB
      enabled: true

# tika configuration
#
tika:
  parsers:
    tesseract-ocr:
      language: eng
      timeout: 1200
      enable-image-processing: true
      apply-rotation: false
      # resize valid range:100-900, DEFAULT is 900, IMPORTANT: must be set in increments of 100
      resize: 100
      # density valid range:150-1200, DEFAULT IS 300
      density: 300
      depth: 16
      filter: "triangle"

    pdf-ocr-parser:
      # deprecated setting, no longer has any impact
      ocr-only-strategy: false
      min-doc-text-length: 1
      min-doc-byte-size: 100
      image-quality: 1.0f
      drop-threshold: 1.0f
      apply-rotation: false
      ocr-detect-angles: false
      # dpi valid range: 0->inf, default from Tika is 300
      ocr-dpi: 200
      use-legacy-ocr-parser-for-single-page-doc: false
      # values: "ALL", "NO_TEXT", "TEXT_ONLY", "VECTOR_GRAPHICS_ONLY"
      ocr-rendering-strategy: "ALL"
      # values: "NONE", "RAW_IMAGES", "RENDER_PAGES_BEFORE_PARSE", "RENDER_PAGES_AT_PAGE_END"
      ocr-image-strategy: "RAW_IMAGES"
      # values:
      #  - "AUTO"
      #  - "NO_OCR" - exactly what it says, it WONT do any OCR
      #  - "OCR_AND_TEXT_EXTRACTION" - OCR and text extraction, WARNING, this will result in DUPLICATED TEXT
      #  - "OCR_ONLY" - only do OCR, without text extraction (this is done separately)
      ocr-strategy: "OCR_ONLY"

    legacy-pdf-parser:
      image-magick:
        timeout: 1200
      tesseract-ocr:
        timeout: 1200
      min-doc-text-length: 10

  post-ocr:
    output-encoding: "UTF-8"
    # if this is set to true, the output text will be UTF-8 compliant, all other chars are removed
    enforce-encoding-output: false

  bulk:
    num-consumers: 8

# documents processing configuration
#
processing:
  use-legacy-tika-processor-as-default: false
  fail-on-empty-files: false
  fail-on-non-document-types: false

logging:
  level:
    root: INFO
    tika.processor: DEBUG
    org.springframework.web: INFO
    service.controller: INFO
    org.hibernate: INFO
  file:
    path: "./"
    name: "app.log"
